FROM python:3.12-slim

RUN pip install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

ENV PATH="${PATH}:${POETRY_VENV}/bin"

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN touch README.md
RUN poetry check
RUN poetry install
COPY ./chesshub-backend /app
EXPOSE 8000

CMD alembic upgrade head && uvicorn src.app:create_app --factory --host 0.0.0.0 --port 8000