"""fix

Revision ID: 4b98a11a8d59
Revises: fa9b42ace997
Create Date: 2025-05-04 21:55:32.731305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b98a11a8d59'
down_revision: Union[str, None] = 'fa9b42ace997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_author_id_fkey', 'article', type_='foreignkey')
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.create_foreign_key('article_author_id_fkey', 'article', 'category', ['author_id'], ['id'])
    # ### end Alembic commands ###
