"""refactor_course

Revision ID: 95df6ce08e78
Revises: c1c103e94a17
Create Date: 2025-06-19 15:14:43.485556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95df6ce08e78'
down_revision: Union[str, None] = 'c1c103e94a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'subtitle')
    # ### end Alembic commands ###
