"""add preview to course

Revision ID: a49f6fc4caac
Revises: 8340b1c0f97b
Create Date: 2025-04-28 23:22:07.507187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49f6fc4caac'
down_revision: Union[str, None] = '8340b1c0f97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('preview', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'preview')
    # ### end Alembic commands ###
