@startuml packages_yourpackage
set namespaceSeparator none
package "infra" as infra {
}
package "infra.auth" as infra.auth {
}
package "infra.auth.jwt" as infra.auth.jwt {
}
package "infra.database" as infra.database {
}
package "infra.database.filters" as infra.database.filters {
}
package "infra.database.reader" as infra.database.reader {
}
package "infra.database.session" as infra.database.session {
}
package "infra.database.sqla_repo" as infra.database.sqla_repo {
}
package "infra.exceptions" as infra.exceptions {
}
package "infra.integrations" as infra.integrations {
}
package "infra.integrations.api" as infra.integrations.api {
}
package "infra.integrations.api_baseclass" as infra.integrations.api_baseclass {
}
package "infra.integrations.api_dataclasses" as infra.integrations.api_dataclasses {
}
package "infra.integrations.api_tests" as infra.integrations.api_tests {
}
package "infra.protocols" as infra.protocols {
}
package "infra.s3" as infra.s3 {
}
package "infra.s3.minio" as infra.s3.minio {
}
infra.integrations.api --> infra.integrations.api_baseclass
infra.integrations.api --> infra.integrations.api_dataclasses
infra.integrations.api_tests --> infra.integrations.api
infra.s3 --> infra.protocols
infra.s3 --> infra.s3.minio
@enduml
